import Head from 'next/head';
import React from 'react';
import styles from '../../../styles/userLogin.module.css'
import Link from 'next/link';

export default function login() {
  return (
    <>
       <Head>
        <title>Create Next App</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"></link>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.body}>
        <div className={styles.content}>
        <img src="/yocodeLogo.jpg" alt = "youcode logo  picture" />
        <br/>    <br/>
        <div className={styles.text}>Welcome to youcode clubs</div>
               <div className={styles.field}>
                    <span className="fa fa-envelope-square"></span>
                    <input type="text" required placeholder="email address" />
                </div>
                <br/>
                <div class={styles.field}>
                    <span class="fa fa-lock"></span>
                    <input type="password" placeholder="password" />
                </div>
                <button>Log in </button>
                <Link href="/">
                  <p  className={styles.goBackLink}>&larr; Back</p>
                </Link>
                <p className={styles.forgetPasswordLink}>Forgot password</p>
                
        </div>
      </main>
    </>
  );
}
