import Head from 'next/head';
import React , {useEffect , useState} from 'react';
import { useRouter } from 'next/router'
import Link from 'next/link'
import axios from 'axios'
import jwt from 'jwt-decode'



export default function navbar({children}) {
const [user , setUser] = useState([]);

  const fetchUserInfo = async () => {
    const token = localStorage.getItem('userToken')
    const id = jwt(token)._id

    await axios.get('http://localhost:3000/api/user/profile/' + id)
         .then (res => {
           setUser(res.data.fetched_user);
         }).catch(err => {
           console.log(err.response.data.message);
         })
  }

  //logging out the user
  const logOut = async() => {
    const token = localStorage.getItem('userToken')
    const id = jwt(token)._id
    console.log(id)
    await axios.post('http://localhost:3000/api/user/logout/' + id)
    .then(res => {
      localStorage.removeItem('adminToken')
      router.push('/')
    })
    .catch(err => console.log(err))
  }


  //intialize
  const router = useRouter()

  //redirect to user profile page
  const redirectToUserProfile = async () => {
     await router.push('/user/profile/')
  }


  useEffect(() => {
    fetchUserInfo()
  }, [])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"></link>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
         <div className="userContentContainer">
           <div className="userIfoSection">
             <div className="userIfoSectionInnerDiv">
                <div className="userRoutesContainer">
                  <Link href="/user/dashboard">
                    <button>
                      <span className="userRouteIcon">
                        <i class="fa fa-home"></i>
                        <span>
                         Home
                       </span>
                      </span>
                      
                    </button>
                  </Link>
                   
                  <Link href="/user/userClub">
                    <button>
                      <span className="userRouteIcon">
                      <i class="fa fa-book"></i>
                       <span>
                         Events
                       </span>
                      </span>
                    </button>
                  </Link>

                  <Link href="/user/chat">
                    <button>
                      <span className="userRouteIcon">
                      <i class="fa fa-comment"></i>
                      <span>
                         Chat
                       </span>
                      </span>
                    </button>
                  </Link>
                </div>
               <img 
                 src={user && user.picture} 
                 alt = "user  picture" 
                 onClick={()=> redirectToUserProfile(1)} 
                /> 
             </div>
           </div>
           <div className="blankDivUser">
                <button className="userLogoutBtn" onClick={logOut}>
                  <i class="fa fa-power-off"></i>
                </button>
           </div>
           <div className="userContentBody">
           {children}
           </div>
           
         </div>
    </>
  );
}