import Head from 'next/head';
import React , {useEffect , useState} from 'react';
import { useRouter } from 'next/router'
import Link from 'next/link'
import axios from 'axios'
import jwt from 'jwt-decode'
import UserProfileImage from './helpers/userPofileImage'
import LogOutBtn from './helpers/logOutBtn';



export default function navbar({children}) {
  const [user , setUser] = useState([]);
  const[isLoggedIn , setIsloggedIn] = useState(false);

  
  //intialize
  const router = useRouter()

  //chekking if user is logged in
  const checkLogging = () => {
    try{
      if(!localStorage.getItem('userToken')){
          setIsloggedIn(false)
          router.push('/user/login')
        }else{
          const token = localStorage.getItem('userToken')
          const isLoggedIn = jwt(token).isLoggedIn
          const role = jwt(token).role
          console.log(role, isLoggedIn)  
          if(role === 'user' && isLoggedIn === true ) {
              setIsloggedIn(true)
            }else{
              router.push('/user/login')
          }
        }
    }
    catch (err){
        console.log(err)
    }
  }

  useEffect(() => {
    checkLogging()
  }, [])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"></link>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      { isLoggedIn ? 
       
        <main>
          <div className="userContentContainer">
            <div className="userIfoSection">
              <div className="userIfoSectionInnerDiv">
                  <div className="userRoutesContainer">
                    <Link href="/user/dashboard">
                      <button>
                        <span className="userRouteIcon">
                          <i class="fa fa-home"></i>
                          <span>
                          Home
                        </span>
                        </span>
                        
                      </button>
                    </Link>
                    
                    <Link href="/user/userClub">
                      <button>
                        <span className="userRouteIcon">
                        <i class="fa fa-book"></i>
                        <span>
                          Events
                        </span>
                        </span>
                      </button>
                    </Link>

                    <Link href="/user/chat">
                      <button>
                        <span className="userRouteIcon">
                        <i class="fa fa-comment"></i>
                        <span>
                          Chat
                        </span>
                        </span>
                      </button>
                    </Link>
                  </div>
                <UserProfileImage/>
              </div>
            </div>
            <div className="blankDivUser">
                  <LogOutBtn/>
            </div>
            <div className="userContentBody">
            {children}
            </div>
            
          </div>
        </main>

        : null
      }
    </>
  );
}