import React , {useState , useEffect} from 'react'
import Head from 'next/head'
import styles from '../../../styles/profile.module.css'
import { Button } from '@material-ui/core'
import SaveIcon from '@material-ui/icons/Save';
import TextField from '@material-ui/core/TextField';
import { toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import jwt from 'jwt-decode'
import axios from 'axios'

export default function profile() {
// admin info
const [superAdmin , setSuperAdmin] = useState([])  

//input states
const [full_name , setFullName] = useState()
const [email , setEmail] = useState()
const [picture , setPicture] = useState()

//input states for reseting password
const [password , setPassword] = useState()
const [newPassword , setNewPassword] = useState()



//get superadmin 
  const getSuperAdminInfo = async () =>{
    const token = localStorage.getItem('token')
    const id = jwt(token)._id
    await axios.get('http://localhost:3000/api/superAdmin/'+ id)
    .then(res => {
      setSuperAdmin(res.data.super_admin)
 
    if(full_name ===  undefined || email ===  undefined ||  email === undefined){
      setFullName(res.data.super_admin.full_name)
      setEmail(res.data.super_admin.email)  
      setPicture(res.data.super_admin.picture)  

      console.log(res.data.super_admin.password)
    } 

    }).catch(err => {
      console.log(err)
    })
  }

//update superadmin information
const updateSuperAdmin = async () => {

  const picture =  await pictureUpload()

  const token = localStorage.getItem('token')
  const id = jwt(token)._id
  await axios.put('http://localhost:3000/api/superAdmin/'+ id,{
    full_name,
    email,
    picture,
  })
  .then(res => {
    getSuperAdminInfo()
    toast.configure()
    toast.success(res.data.message)
    
  }).catch(err => {
    toast.configure()
    toast.error(err.response.data.message)
  })

}

//uploading image using cloudinary
const pictureUpload = async () => {

  const data = new FormData()
  data.append("file", picture  )
  data.append("upload_preset", "youcodeClubs")
  data.append("cloud_name", "dtq13h9rg" )


  const res = await fetch("	https://api.cloudinary.com/v1_1/dtq13h9rg/image/upload",{
    method : "POST",
    body : data
  })
  const res2 = await res.json() 
  console.log(res2);
  return res2.url
}


//ResetPassword
const ressetPassword = async (req, res) => {
  const token = localStorage.getItem('token')
  const id = jwt(token)._id

  console.log(password , newPassword);
   await axios.put('http://localhost:3000/api/superAdmin/resetPassword/' + id,{
     password,
     newPassword
   })
   .then(res => {
      getSuperAdminInfo()
      toast.configure()
      toast.success(res.data.message)
      emptyInputs()
   }).catch(err => {
      toast.configure()
      toast.error(err.response.data.message)
   })

}


//emptyInputs
const emptyInputs = () => {
  document.querySelector('#password').value = ''
  document.querySelector('#NewPassword').value = ''
}

useEffect(() => {
    getSuperAdminInfo()
}, [])


  return (
    <>
      <Head>
        <title>Create Next Ap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"></link>
        <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      </Head>
      <main>
        <div className={styles.profileContainer}>
          <div className={styles.profileImageSection}>
              <div className={styles.profileImage}>
                <img src={superAdmin.picture} alt="super admin picture" />
              </div>
          </div>
          <br/>
          <div className={styles.profileInfoSection}>
                <label htmlFor="full_name" class="form-label">Full Name</label>
                <input
                    className={styles.inputCustomStyle}
                    defaultValue={superAdmin.full_name}
                    id='full_name'
                    type="text"
                    onChange={(e)=>{setFullName(e.target.value)}}
                />
                <br/> <br/>
                <label htmlFor="email" class="form-label">Email address</label>
                <input 
                   className={styles.inputCustomStyle}
                   id='email'
                   defaultValue={superAdmin.email}
                   type="email"
                   onChange={(e)=>{setEmail(e.target.value)}}
                />
                <br/> <br/>
                 <div class="mb-3">
                      <label htmlFor="formFile" class="form-label">Choose an Image</label>
                      <input 
                        class="form-control" type="file" id="formFile"  
                        onChange={(e)=>setPicture(e.target.files[0])}
                      />
                  </div>
                <Button
                    variant="contained"
                    color="primary"
                    size="large"
                    startIcon={<SaveIcon />}
                    onClick={updateSuperAdmin}
                >
                    Save
                </Button>
          </div>
        </div>
        <br/>
        <div className={styles.resetPasswordContainer}>
          <h1>Reset Password</h1>
            <TextField 
              label="Current Password"
              variant="filled"
              fullWidth
              id="password"
              type="password"
              onChange={(e)=>{setPassword(e.target.value)}}
            />
            <br/><br/>
            <TextField 
              label="New Password"
              variant="filled"
              fullWidth
              id="NewPassword"
              type="password"
              onChange={(e)=>{setNewPassword(e.target.value)}}
            />
            <br/> <br/>
             <Button
                    variant="contained"
                    color="primary"
                    size="large"
                    startIcon={<SaveIcon />}
                    onClick={ressetPassword}
                >
                    Save
             </Button>
        </div>
        <div className={styles.extraSpace}></div>
      </main>
    </>
  );
}


