import Head from 'next/head';
import React , {useEffect , useState} from 'react';
import { useRouter } from 'next/router'
import Link from 'next/link'
import axios from 'axios'
import jwt from 'jwt-decode'

export default function logOutBtn() {
    //intialize
    const router = useRouter()

 //logging out the user
  const logOut = async() => {
    const token = localStorage.getItem('userToken')
    const id = jwt(token)._id
    console.log(id)
    await axios.post('http://localhost:3000/api/user/logout/' + id)
    .then(res => {
      localStorage.removeItem('userToken')
      router.push('/')
    })
    .catch(err => console.log(err))
  }
  return (
    <>
        <Head>
            <title>Create Next App</title>
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"></link>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <button className="userLogoutBtn" onClick={logOut}>
            <i class="fa fa-power-off"></i>
        </button>
    </>
  );
}
