import Head from 'next/head'
import React , {useState , useEffect} from 'react';
import styles from '../styles/userView.module.css'
import axios from 'axios'
import ExploreIcon from '@material-ui/icons/Explore';
import IconButton from '@material-ui/core/IconButton';
import Tooltip from '@material-ui/core/Tooltip';
import { Button } from '@material-ui/core';

export default function Home() {

// club states  
const [clubs , setClubs] = useState([])
const [dataReady , setDataReady] = useState(false)
const [club , setClub] = useState([])


//get all clubs 
const getAllClubs = async () => {
  await axios.get("http://localhost:3000/api/superAdmin/clubs")
  .then( res => {
      setClubs(res.data.clubs)
      
  }).catch(err =>{
      console.log(err);
  })
}

const getSingleClub = async ( id) => {
  console.log(id)
  await axios.get('http://localhost:3000/api/admin/club/' + id)
  .then( res => {
      setClub(res.data.club)
      setDataReady(true)
  }).catch(err =>{
      console.log(err);
  })
}

useEffect (() => {
  getAllClubs()
},[])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.sliderContainer}>
          <div className={styles.sliderImageContainer}>
              { dataReady ?
                <img src={club.picture} alt="club picture" /> : 
                <img src="/YouCode.gif" alt="club picture" />
              }
          </div>
          <div className={styles.detailsContainer}>
          <Button className={styles.loginBtn}>Log in</Button>
            <div className={styles.outerContainer}>
              <div className={styles.innerContainer}>
                {dataReady ?
                  <>
                    <Button 
                      className={styles.joinBtn}
                    >
                        Join now
                    </Button>
                      <h2>{club.name}</h2>
                      <p> {club.description} </p>
                  </> 
                 :
                 <>
                      <h2>Youcode clubs</h2>
                      <p>welcome dear youcoders , youcode is not just about coding , it also about improving other skills , and there is no better way then joining a one of it's clubs , there plenty of clubs , just select a club from the list down and join what represent your interests , or if you are already in ,  just simply log in </p>
                  </> 
                }
              </div>
              {dataReady ? 
                  <Tooltip title="Explore moreDetails " >
                  <IconButton aria-label="Explore moreDetails"
                    className={styles.exploreBtn}
                  >
                      <ExploreIcon />   
                  </IconButton>
                </Tooltip>
               :
                null
              } 
              <div className={styles.paginationDiv}>
                {clubs.map(club =>{
                  return (
                    <div 
                      key={club._id}  
                      onClick={()=> getSingleClub(club._id)}
                    >
                      <img src={club.picture} alt="club pic" />
                    </div>
                  )
                })}
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
