import Head from 'next/head';
import React , {useEffect , useState} from 'react';
import styles from '../../../styles/userLogin.module.css'
import Link from 'next/link';
import { useRouter } from 'next/router';
import axios from 'axios'
import { toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import jwt from 'jwt-decode'


export default function verifyAcount() {
  const [activationCode , setActivationCode] = useState('')

  // initial use router  
  const router = useRouter()

  const verifyActivationCode = async () => {
      const token = localStorage.getItem('userToken')
      const id = jwt(token)._id

      await axios.post(' http://localhost:3000/api/user/checkVerificationCode',{
        id,
        activationCode,
      }).then(res =>{
        toast.configure()
       toast.success(res.data.message)
       router.push('/user/dashboard')
      }).catch(err => {
        toast.configure()
        toast.error(err.response.data.message)
      })
     
  }

  
  return (
    <>
        <Head>
            <title>Create Next App</title>
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"></link>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.body}>
            <div className={styles.content}>
            <img src="https://is4-ssl.mzstatic.com/image/thumb/Purple125/v4/60/23/9d/60239d01-4fdf-fb7b-e2d2-a1d3bf4835b0/source/512x512bb.jpg" alt = "youcode logo  picture" />
            <br/>    <br/>
            <div className={styles.text}>
                verify your acound
            </div>
            <div className={styles.field}>
                <span className="fa fa-check-circle"></span>
                <input 
                  type="text" required placeholder="verification code"
                  onChange={(e) => setActivationCode(e.target.value)} 
                />
            </div>
            <br/>
            <button onClick={verifyActivationCode}>verify</button>    
            </div>
       </main>
    </>
  );
}
