import Head from 'next/head';
import React , {useEffect , useState} from 'react';
import styles from '../../../styles/userForgetPassword.module.css'
import Link from 'next/link';
import { useRouter } from 'next/router';
import axios from 'axios'
import { toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import jwt from 'jwt-decode'


export default function forgetPassword() {
  const [password , setPassword] = useState('')

  // initial use router  
  const router = useRouter()

  //get the reset token from the url parameters
  const {id} = router.query

  //update password
  const updatePassword = async () => {
    const resetToken = id
  
    await axios.put('https://youcode-clubs.vercel.app/api/user/forgetPassword/' + resetToken,{
      password
    }).then(res =>{
      //empty password field
      document.querySelector('#password').value = '';

      //send success message
      toast.configure()
      toast.success(res.data.message)

      //redirect to login home 
      setTimeout(() =>{
        router.push("/user/login");
      }, 1500)
    }).catch(err =>{
      toast.configure()
      toast.error("err.response.data.message")
    })
  }


  return (
    <>
       <Head>
        <title>Create Next App</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"></link>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.body}>
        <div className={styles.content}>
            <img src="/resetPassword.jpg" alt = "reset password  picture" />
            <br/>    <br/>
            <div className={styles.text}>
               Please enter your new password, and make sure to remember it
            </div>
            <div className={styles.field}>
                <span className="fa fa-lock"></span>
                <input
                    type="password" 
                    required
                    id="password" 
                    placeholder="new password" 
                    onChange={(e)=> setPassword(e.target.value)}
                />
            </div>
           
            <button onClick={updatePassword}>Reset Password</button>
            <Link href="/">
                <p  className={styles.goBackLink}>&larr; Back</p>
            </Link>    
        </div>
      </main>
    </>
  );
}
