import Head from 'next/head';
import React , {useEffect , useState} from 'react';
import styles from '../../../styles/userForgetPassword.module.css'
import Link from 'next/link';
import { useRouter } from 'next/router';
import axios from 'axios'
import { toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import jwt from 'jwt-decode'


export default function forgetPassword() {
  const [email , setEmail] = useState('')

  // initial use router  
  const router = useRouter()


  return (
    <>
       <Head>
        <title>Create Next App</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"></link>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.body}>
        <div className={styles.content}>
            <img src="/resetPassword.jpg" alt = "reset password  picture" />
            <br/>    <br/>
            <div className={styles.text}>
               Please enter your new password, and make sure to remember it
            </div>
            <div className={styles.field}>
                <span className="fa fa-lock"></span>
                <input
                    type="password" required placeholder="new password" 
                    onChange={(e)=> setEmail(e.target.value)}
                />
            </div>
           
            <button>Reset Password</button>
            <Link href="/">
                <p  className={styles.goBackLink}>&larr; Back</p>
            </Link>    
        </div>
      </main>
    </>
  );
}
