import Head from 'next/head';
import React , {useEffect , useState} from 'react';
import styles from '../../../styles/userForgetPassword.module.css'
import Link from 'next/link';
import { useRouter } from 'next/router';
import axios from 'axios'
import { toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import jwt from 'jwt-decode'


export default function forgetPassword() {
  const [password , setPassword] = useState('')
  const [email , setEmail] = useState('')

  //send an a reset link in mail
  const SendResetToken = async () => {
    await axios.post ('https://youcode-clubs.vercel.app/api/user/forgetPassword',{
      email
    }).then(res =>{
      //empty input
      document.querySelector("#email").value = ""

      //send notifaction
      toast.configure()
      toast.success(res.data.message)

    }).catch(err =>{
      toast.configure()
      toast.error(err.response.data.message)
    })
  }

  // initial use router  
  const router = useRouter()


  return (
    <>
       <Head>
        <title>Create Next App</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"></link>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.body}>
        <div className={styles.content}>
            <img src="/forgetPassword.png" alt = "forget password  picture" />
            <br/>    <br/>
            <div className={styles.text}>
                Please enter your email address , and wait for an email to reset your password
            </div>
            <div className={styles.field}>
                <span className="fa fa-envelope-square"></span>
                <input
                    type="email" id="email" required placeholder="email address" 
                    onChange={(e)=> setEmail(e.target.value)}
                />
            </div>
           
            <button onClick={SendResetToken}>Reset Password</button>
            <Link href="/">
                <p  className={styles.goBackLink}>&larr; Back</p>
            </Link>    
        </div>
      </main>
    </>
  );
}
